PREFIX uni:<http://www.mydomain.org/uni-ns#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?capacity
WHERE {   
    ?x      rdf:type   uni:Classroom;
            uni:room_name   ?name;
            uni:room_capacity  ?capacity
            FILTER(?capacity > "100")
}